# Generated by Django 4.0.1 on 2022-02-25 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shelf',
        ),
    ]
